services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=robert
      - DATABASE_PASSWORD=1
      - DATABASE_NAME=myAgathaApp_development
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Bind mount for live reload
    # Remove the command override
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=robert
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=myAgathaApp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: